# Pandas

Na aula de hoje, vamos explorar os seguintes tópicos em Python:

- 1) Pandas
- 2) <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html">Documentação - Series</a>
- 3) <a href="https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html">Quick started</a>

___

## 1) Pandas

O **Pandas** é uma das bibliotecas mais usadas em data science.

Esta biblioteca, construída a partir do Numpy, possibilita a estruturação e manipulação de dados de maneira simples e eficiente.

Comos os dados são a matéria prima de todo projeto de data science, manipulá-los é fundamental! Por isso, utilizaremos o Pandas em quase todas as aulas daqui pra frente!

Para entendermos melhor o pandas e passar a utilizá-lo, precisamos entender suas estruturas fundamentais: as **Series** e o **DataFrame**.

Começamos importando o pandas:

In [18]:
# !pip install pandas

In [22]:
# instalar pandas
# pip install pandas
# importando o pandas
import pandas as pd
import numpy as np

### Series

O objeto fundamental do Pandas são as **Series**, uma classe do pandas.

As Series são as **colunas das tabelas** (que veremos mais a frente), e por baixo dos panos, os dados ficam armazenados como **numpy arrays**!

A diferença é que a série possui um **índice associado**, permitindo o acesso aos conteúdos dessa estrutura por ele, como um dicionário.

Além disso, as séries têm métodos específicos além dos que vimos pra arrays, o que será super útil!

Podemos criar uma série **a partir de uma lista**, usando a função do pandas `pd.Series()`:

In [23]:
lista = [4, 6, 3, 7, 25]

In [24]:
arr = np.array(lista)

In [25]:
arr

array([ 4,  6,  3,  7, 25])

In [26]:
# série a partir de lista
# os índices serão automaticamente definidos como números inteiros
serie = pd.Series(data=lista)

In [27]:
serie

0     4
1     6
2     3
3     7
4    25
dtype: int64

In [31]:
#dir(serie)

In [32]:
serie.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
list(serie.index)

[0, 1, 2, 3, 4]

In [34]:
for ind in serie.index:
  print(ind)

0
1
2
3
4

In [37]:
serie2 = pd.Series(data=lista, index=['a', 'b', 'c', 'd', 'e'])
serie2

a     4
b     6
c     3
d     7
e    25
dtype: int64

In [58]:
serie2 = pd.Series(data=lista, index=('a', 'b', 'c', 'd', 'e'))
serie2

a     4
b     6
c     3
d     7
e    25
dtype: int64

In [48]:
# gerar um erro
serie2 = pd.Series(data=lista, index=('a', 'b', 'c', 'd'))
serie2

ValueError: ignored

In [40]:
# Podemos indexar a série, normalmente:
serie[2]

3

In [41]:
serie[1]

6

In [43]:
serie[3:]

3     7
4    25
dtype: int64

In [51]:
serie2[0]

4

In [53]:
# acessar pelo "nome" da linha
serie2.loc['a']

4

In [55]:
serie2.loc['a'] = 1000
serie2

a    1000
b       6
c       3
d       7
e      25
dtype: int64

In [56]:
for ind, valor in enumerate(serie2.index):
  if valor == 'd':
    print(ind)

3

In [57]:
serie2.index.get_loc('d')

3

In [44]:
serie.values

array([ 4,  6,  3,  7, 25])

In [ ]:
list(range(0, 5, 1))

[0, 1, 2, 3, 4]

In [45]:
# slicing
serie[2:]

2     3
3     7
4    25
dtype: int64

In [46]:
serie[0] = 100

In [47]:
serie

0    100
1      6
2      3
3      7
4     25
dtype: int64

In [63]:
serie3 = pd.Series(data=lista,
                   index=('a', 'b', 'c', 'd', 'e'),
                   name='Numeros',
                   dtype=int)
serie3

a     4
b     6
c     3
d     7
e    25
Name: Numeros, dtype: int64

In [61]:
serie3.dtype

dtype('int64')

In [ ]:
# alguns filtros

In [64]:
serie3[serie3==3]

c    3
Name: Numeros, dtype: int64

In [65]:
## pares
serie3[serie3 % 2 == 0]

a    4
b    6
Name: Numeros, dtype: int64

In [15]:
# Algumas estatísticas: max, min, mean e describe

In [66]:
serie.max()

100

In [67]:
serie.min()

3

In [68]:
serie.describe()

count      5.000000
mean      28.200000
std       41.057277
min        3.000000
25%        6.000000
50%        7.000000
75%       25.000000
max      100.000000
dtype: float64

In [69]:
serie.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 168.0 bytes

É possível definir os índices como quisermos

In [70]:
peso = pd.Series(data=[4, 6, 8, 9],
                   name='Peso',
                   dtype=int)

altura = pd.Series(data=[6, 7, 9, 3],
                   name='Altura',
                   dtype=int)
peso

0    4
1    6
2    8
3    9
Name: Peso, dtype: int64

In [71]:
altura

0    6
1    7
2    9
3    3
Name: Altura, dtype: int64

In [72]:
df = pd.DataFrame(
    data={
        "Peso": peso,
        "Altura": altura
    }
)
df

   Peso  Altura
0     4       6
1     6       7
2     8       9
3     9       3

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8698287873877782794, *['index'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8698287873877782794, *['Peso'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8698287873877782794, *['Altura'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8698287873877782794, *['index'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8698287873877782794, *['Peso'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8698287873877782794, *['Altura'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def scatter_plots(df, colname_pairs, scatter_plot_size=2.5, size=8, alpha=.6):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * scatter_plot_size, scatter_plot_size))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    ax.scatter(df[x_colname], df[y_colname], s=size, alpha=alpha)
    plt.xlabel(x_colname)
    plt.ylabel(y_colname)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df_8698287873877782794, *[[['index', 'Peso'], ['Peso', 'Altura']]], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8698287873877782794, *['index', 'Altura', None], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8698287873877782794, *['index', 'count()', None], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8698287873877782794, *['Peso', 'Altura', None], **{})
chart

import numpy as np
from google.colab import autoviz
df_8698287873877782794 = autoviz.get_df('df_8698287873877782794')

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figsize=(2.5, 1.3), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df_8698287873877782794, *['Peso', 'count()', None], **{})
chart

In [74]:
pd.DataFrame(data=[
    peso,
    altura
])

        0  1  2  3
Peso    4  6  8  9
Altura  6  7  9  3

In [81]:
df3 = pd.DataFrame(
    data=np.random.rand(3, 4),
    columns=["col1", "col2", "col3", "col4"],
    index=["a", "b", "c"]
)
df3

       col1      col2      col3      col4
a  0.006710  0.649717  0.598137  0.165055
b  0.538862  0.719406  0.471708  0.082997
c  0.286579  0.875182  0.774661  0.892414

In [82]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      float64
 1   col2    3 non-null      float64
 2   col3    3 non-null      float64
 3   col4    3 non-null      float64
dtypes: float64(4)
memory usage: 228.0+ bytes

In [83]:
df3['col2'] = df3['col2'].astype(str)
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      float64
 1   col2    3 non-null      object
 2   col3    3 non-null      float64
 3   col4    3 non-null      float64
dtypes: float64(3), object(1)
memory usage: 228.0+ bytes

In [84]:
df3 = df3.astype(float)

In [85]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      float64
 1   col2    3 non-null      float64
 2   col3    3 non-null      float64
 3   col4    3 non-null      float64
dtypes: float64(4)
memory usage: 228.0+ bytes

In [86]:
df3.describe()

           col1      col2      col3      col4
count  3.000000  3.000000  3.000000  3.000000
mean   0.277384  0.748102  0.614835  0.380155
std    0.266195  0.115439  0.152165  0.445523
min    0.006710  0.649717  0.471708  0.082997
25%    0.146645  0.684562  0.534923  0.124026
50%    0.286579  0.719406  0.598137  0.165055
75%    0.412720  0.797294  0.686399  0.528735
max    0.538862  0.875182  0.774661  0.892414

### DataFrame

Agora que conhecemos as séries, vamos partir pro objeto do Pandas que mais utilizaremos: o **DataFrame**

Como veremos a seguir, o DataFrame é uma estrutura que se assemalha a uma **tabela**.

Estruturalmente, o DataFrame nada mais é que um **conjunto de Series**, uma para cada coluna (e, claro, com mesmo índice, que irão indexar as linhas).

Veremos depois como **ler um dataframe a partir de um arquivo** (que é provavelmente a forma mais comum)

Há muitas formas de construir um DataFrame do zero. Todas elas fazem uso da função **pd.DataFrame()**, como veremos a seguir.

Se quisermos especificar os índices de linha, o nome das colunas, e os dados, podemos passá-los separadamente:

In [5]:
# ler arquivo csv para um dataframe

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Exercícios

Leia a base de dados <a href="https://drive.google.com/file/d/19BKYaNr4_wNd9EESz8Wo962t56rKCx-v/view?usp=drive_link">Titanic</a> disponível no Kaggle e realize as seguintes análises:

In [90]:
import pandas as pd
titanic_df = pd.read_csv("/content/drive/MyDrive/Ada/1015/train.csv")
titanic_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [92]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

1.   Mostre o número de mulheres e homens que estavam no navio.

In [95]:
## solucao 1
male = titanic_df[titanic_df['Sex']=='male'].shape[0]
female = titanic_df[titanic_df['Sex']=='female'].shape[0]
print(f"male: {male} female: {female}")

male: 577 female: 314

In [97]:
## solucao 2
male = titanic_df[titanic_df['Sex']=='male']['Sex'].count()
female = titanic_df[titanic_df['Sex']=='female']['Sex'].count()
print(f"male: {male} female: {female}")

male: 577 female: 314

In [109]:
# solucao 3
titanic_df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [106]:
# solucao 4
titanic_df.groupby(by='Sex').count().reset_index()['PassengerId']

0    314
1    577
Name: PassengerId, dtype: int64

In [108]:
# solucao 5
titanic_df.groupby(by='Sex').count().reset_index()[['Sex', 'PassengerId']]

      Sex  PassengerId
0  female          314
1    male          577

In [112]:
# solucao 6 - female
titanic_df[titanic_df.Sex == 'female']['Sex'].value_counts()

female    314
Name: Sex, dtype: int64

In [114]:
titanic_df.groupby(
    by=['Embarked', 'Pclass', 'Sex']
).count().reset_index()[['Sex', 'Embarked', 'Pclass', 'PassengerId']]

       Sex Embarked  Pclass  PassengerId
0   female        C       1           43
1     male        C       1           42
2   female        C       2            7
3     male        C       2           10
4   female        C       3           23
5     male        C       3           43
6   female        Q       1            1
7     male        Q       1            1
8   female        Q       2            2
9     male        Q       2            1
10  female        Q       3           33
11    male        Q       3           39
12  female        S       1           48
13    male        S       1           79
14  female        S       2           67
15    male        S       2           97
16  female        S       3           88
17    male        S       3          265

In [124]:
# pegar pelo index? MultiIndex: https://pandas.pydata.org/docs/user_guide/advanced.html
titanic_df.groupby(
    by=['Embarked', 'Pclass', 'Sex']
).value_counts()

Embarked  Pclass  Sex     PassengerId  Survived  Name                                                               Age   SibSp  Parch  Ticket             Fare     Cabin
C         1       female  2            1         Cumings, Mrs. John Bradley (Florence Briggs Thayer)                38.0  1      0      PC 17599           71.2833  C85      1
                          53           1         Harper, Mrs. Henry Sleeper (Myna Haxtun)                           49.0  1      0      PC 17572           76.7292  D33      1
                          557          1         Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")  48.0  1      0      11755              39.6000  A16      1
                          592          1         Stephenson, Mrs. Walter Bertram (Martha Eustis)                    52.0  1      0      36947              78.2667  D20      1
                          642          1         Sagesser, Mlle. Emma                                               24.0  0      0      PC 17477           69.3000  B35      1
                                                                                                                                                                            ..
S         3       male    76           0         Moen, Mr. Sigurd Hansen                                            25.0  0      0      348123             7.6500   F G73    1
                          430          1         Pickard, Mr. Berk (Berk Trembisky)                                 32.0  0      0      SOTON/O.Q. 392078  8.0500   E10      1
                          700          0         Humblen, Mr. Adolf Mathias Nicolai Olsen                           42.0  0      0      348121             7.6500   F G63    1
                          716          0         Soholt, Mr. Peter Andreas Lauritz Andersen                         19.0  0      0      348124             7.6500   F G73    1
                          752          1         Moor, Master. Meier                                                6.0   0      1      392096             12.4750  E121     1
Length: 183, dtype: int64

In [130]:
titanic_df.groupby(
    by=['Embarked', 'Pclass', 'Sex']
).value_counts().index

MultiIndex([('C', 1, 'female',   2, 1, ...),
            ('C', 1, 'female',  53, 1, ...),
            ('C', 1, 'female', 557, 1, ...),
            ('C', 1, 'female', 592, 1, ...),
            ('C', 1, 'female', 642, 1, ...),
            ('C', 1, 'female', 701, 1, ...),
            ('C', 1, 'female', 711, 1, ...),
            ('C', 1, 'female', 717, 1, ...),
            ('C', 1, 'female', 743, 1, ...),
            ('C', 1, 'female', 836, 1, ...),
            ...
            ('S', 3, 'female',  11, 1, ...),
            ('S', 3, 'female', 206, 0, ...),
            ('S', 3, 'female', 252, 0, ...),
            ('S', 3, 'female', 395, 1, ...),
            ('S', 3, 'female', 824, 1, ...),
            ('S', 3,   'male',  76, 0, ...),
            ('S', 3,   'male', 430, 1, ...),
            ('S', 3,   'male', 700, 0, ...),
            ('S', 3,   'male', 716, 0, ...),
            ('S', 3,   'male', 752, 1, ...)],
           names=['Embarked', 'Pclass', 'Sex', 'PassengerId', 'Survived', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin'], length=183)

In [131]:
## reset_index
titanic_df.groupby(
    by=['Embarked', 'Pclass', 'Sex']
).value_counts().reset_index()[['Embarked', 'Pclass', 'Sex']]

    Embarked  Pclass     Sex
0          C       1  female
1          C       1  female
2          C       1  female
3          C       1  female
4          C       1  female
..       ...     ...     ...
178        S       3    male
179        S       3    male
180        S       3    male
181        S       3    male
182        S       3    male

[183 rows x 3 columns]

2. Mostre a quantidade de sobreviventes do acidente (Suvirved)

In [145]:
# titanic_df[titanic_df.Survived == 1].value_counts()

In [142]:
titanic_df[titanic_df.Survived == 1]['Survived'].value_counts()

1    342
Name: Survived, dtype: int64

In [146]:
titanic_df[titanic_df.Survived == 1]['Survived'].sum()

342

In [147]:
titanic_df['Survived'].sum()

342

3. Conte os diferentes tipos de *Embarked* contidos na base de dados.

In [137]:
# groupby
titanic_df.groupby(
    'Embarked'
)['PassengerId'].count().reset_index().sort_values(by='PassengerId', ascending=False)

  Embarked  PassengerId
2        S          644
0        C          168
1        Q           77

In [134]:
# values_counts
titanic_df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

4. Quantas classes (coluna Pclass) existem na base de dados?

In [140]:
titanic_df['Pclass'].unique().shape[0]

3

5. Qual a pessoa mais velha que estava a bordo?

In [160]:
# ordenar decrescente
titanic_df.sort_values(by='Age', ascending=False)[:1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

In [162]:
# usando argmax
indice = titanic_df['Age'].argmax()
titanic_df.iloc[indice]

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object

In [203]:
max = float(titanic_df['Age'].max())
titanic_df[titanic_df.Age==max]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

6. Qual a pessoa mais velha que sobreviveu?

In [218]:
# problema no reindex?
resultado = titanic_df[titanic_df.Survived != 0].copy()
resultado = resultado.reset_index()
resultado.sort_values(by='Age', ascending=False)
indice = resultado['Age'].argmax()
resultado.iloc[indice]

index                                           630
PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 247, dtype: object

In [211]:
resultado = titanic_df[titanic_df.Survived != 0].copy()
resultado.sort_values(by='Age', ascending=False)[:1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

In [179]:
indice = titanic_df[titanic_df.Survived==1]['Age'].argmax()
titanic_df.iloc[indice]
indice

247

In [170]:
titanic_df[titanic_df.Survived==1].sort_values(by='Age', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
727,728,1,3,"Mannion, Miss. Margareth",female,NaN,0,0,36866,7.7375,NaN,Q
740,741,1,1,"Hawksford, Mr. Walter James",male,NaN,0,0,16988,30.0000,D45,S
828,829,1,3,"McCormack, Mr. Thomas Joseph",male,NaN,0,0,367228,7.7500,NaN,Q
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C

A pessoa mais velha a bordo sobreviveu? Sim: 1 ou Não: 0

In [169]:
max = float(titanic_df['Age'].max())
is_alive = 'Não' if int(titanic_df[titanic_df.Age==max]['Survived']) == 0 else 'Sim'
is_alive

'Sim'

7. Qual o sexo da pessoa mais jovem que estava a bordo?

8. Em qual classe (Pclass) estava a pessoa mais jovem a bordo?